### ISSUE TITLE
Some MIUI domains

### ISSUE THREAD

**Issue by pidus** [AdAway/adaway.github.io#102]
* fr-app-chat-global-xiaomi-net-1516654448.eu-central-1.elb.amazonaws.com
* fr-app-chat-global-xiaomi-net1-1667981913.eu-central-1.elb.amazonaws.com
* fr.app.chat.global.xiaomi.net
* resolver-msg-global-xiaomi-net02-1367306752.ap-south-1.elb.amazonaws.com
* resolver.msg.global.xiaomi.net
* metok-ccc.intl.xiaomi.com

Found these on EU ROM. 

Thanks.

**Comment by jawz101** [comment]
What happened when you blocked them manually?  I'm not sure they are tracking or ads w/o more info

**Comment by pidus** [comment]
Nothing breaks on my end. Yeah I'm not sure about their purpose. But they phone home incessantly.

**Comment by jawz101** [comment]
I'd try blocking them in adaway first.  Or disabling the apps that may cause it.
My hesitations are if it breaks an expected function or, if they are blocked, does it cause the lookups to cease or do they increase because it wants to continuously retry... thereby draining battery.

I want to go through the list and see if any cause this latter issue because I don't want to drain battery for the sake of one block.

**Comment by pidus** [comment]
I have them blocked ever since I found them. Just like most other sketchy MIUI domains not covered by any block list. Never had any issues. But yeah, by the looks of it these sites don't scream *tracking* like some other MIUI domains which are blocked in Steven Black's list. It's totally possible they are related to some features that I personally never used. So it would be prudent not to block them.

**Comment by jawz101** [comment]
not adding

**Comment by spirillen** [comment]
> not adding

Reason?
