### ISSUE TITLE
Add domain to adaway host file

### ISSUE THREAD

**Issue by desk7** [AdAway/adaway.github.io#106]
I've found that many android apps connect to `firebaseinstallations.googleapis.com`.
Do you think it could be added to Adaway host file?

**Comment by jawz101** [comment]
I'm hesitant on blocking anything ***.googleapis.com.  https://firebase.google.com/docs/reference/android/com/google/firebase/installations/FirebaseInstallations

Have you blocked it on your end and seen how apps behave?  I have this concern it might break something like any app that uses cloud messaging

**Comment by spirillen** [comment]
I have it blocked in-house with no issues

![image](https://user-images.githubusercontent.com/44526987/90310728-9ae05100-def4-11ea-9502-4779b1bedb70.png)


For the curious:

If you noticed I for once didn't return a NXDOMAIN (rcode 3) to this rule, then it because my Denon Radio is broken, you can read more about that issue here <https://www.mypdns.org/T66>

**Comment by llacb47** [comment]
Yes, spirillen is also blocking a bunch of other google services.  Take everything they say with a substantial grain of salt. https://github.com/anudeepND/blacklist/issues/111#issuecomment-659552352

**Comment by jawz101** [comment]
not adding
