### ISSUE TITLE
Bugfender compatibility report

### ISSUE THREAD

**Issue by jgimenez** [AdAway/adaway.github.io#111]
**Describe the third party app**
 - Name: Bugfender SDK
 - Version: 3.0.5

**Describe the compabitily issue**
The application does not seem to be able to reach to the server on api.bugfender.com.

**Workaround**
If applicable, describe the whitelist domains to add to fix the issue:
 - api.bugfender.com

Please add tag `workaround-available` if a work around is available.

**Comment by jgimenez** [comment]
Ah, there's a separate repo for the list. Sorry, I didn't know that.

**Comment by jawz101** [comment]
Are email addresses grabbed from the device by the SDK?  I've just been spending time looking over your site to see what all it does (what data it gets, edge cases, etc.) as well as see what sorts of apps use the SDK [Exodus reports](https://reports.exodus-privacy.eu.org/en/trackers/233/).

This list isn't just necessarily ads.  Trackers and simply traffic unnecessary for the end user to operate an app might improve privacy or simply save a user data.  If some app is collecting tons of logs and shooting them back off of your device, that might be a privacy issue if it contains PII or a data hog.  (e.g. [link](https://www.washingtonpost.com/technology/2019/12/17/what-does-your-car-know-about-you-we-hacked-chevy-find-out/))

>Modern vehicles don’t just have one computer. There are multiple, interconnected brains that can generate up to 25 gigabytes of data per hour from sensors all over the car.

I can't just take the company CEO's word for it, but I'm willing to understand.

**Comment by spirillen** [comment]
Nice write @jawz101 :+1: And I do agree with you.

But a domain that sells it self by (there own words) 
> Bugfender lets you see your mobile or web application logs remotely for any given user
> Bugfender is battery and network efficient and keeps logging even if the device is offline.

Then I'm ready to keep them blocked.

As we have been seeing so many times before, by actual breaking down there code, it always turns out to be trackware that is getting sold for the lowest bidder on the open marked.

And "Trusted by thousands"  Seriously, how about trusted by any users?? These companies are not exactly on my list for birthday invitations.

![image](https://user-images.githubusercontent.com/44526987/91635595-08fb3c80-e9fa-11ea-939a-a9dcfc858061.png)

My opinion: Keep Blocking as you haven't got any "it breaks reports" (Which I understand you do like to do)

**Comment by jgimenez** [comment]
Hi there, Bugfender is a privacy-respecting tool for software developers to be able to debug and resolve bugs faster. Bugfender helps developers collect logs from their own application, with controls on which data is being collected and which devices are sending data. Bugfender does not collect any names, emails or advertisement identifiers. Whilst Bugfender does not provide any UI, developers can show a UI to enable or disable Bugfender if they wish. Also Bugfender has modes to send logs only in specific situations, such as when the app crashes or when the user actively wants to send feedback.

Also on the company policy: Bugfender does not use the collected data for their own purposes or resell this data to third parties. If you'd like to learn more about security/privacy, you can check the [Security page](https://bugfender.com/security/) and the [Terms of Service](https://bugfender.com/terms-of-service/) (especially section 3.2). So, essentially, Bugfender is comparable to say, an Amazon S3 bucket, just specialized on certain tasks.

**Comment by jawz101** [comment]
My stance still stands because I've mentioned criteria that likely no logging, tracking nor ad company would care to implement my

It would be over engineered to inform the user as much as the developer.

**Comment by spirillen** [comment]
Big applause to @jawz101 :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap:

**Comment by jgimenez** [comment]
I understand your decision, although of course I do not share it. Developers can fetch all the data they want without the need of any external tools. Bugfender only helps them the data they need for debugging purposes.

I think you're treating all SDKs the same, regardless of what's the use of the data. Bugfender is a tool of the developer, the data stays with them. Other SDKs like Google or Facebook provide some functionality to the developer, but also use the data for their own benefit, such as advertisement.

**Comment by jawz101** [comment]
Oh I don't treat them all the same.  You just haven't done much to alleviate the concerns I've said- like at all.  And if you do say devs can already fetch this stuff w/o the need for external tools- well, true.  I mean you are just making that bit of code easier to implement.  It's a small community of people who make blocklists and we each have our opinions.

I mean, if you wanted to make it difficult on me you could make each of your customers have to connect to a subdomain that is represented by a unique identifer (e.g. 2342asdfvadf234234.api.bugfender.com).  That would annoy me and I would avoid messing with trying to block every one of them.  But then there are also other ad blockers out there that support fancier syntax such as regex and wildcards to do pattern matching (eg ^.*bugfender\.com).

I'm just saying there are people that want their devices to be as quiet on the network as possible, but still do the one purpose (say, shop in a shopping app or Netflix it up) and not have their particular device be apart of the diagnostic process 24/7.  That's just how it is.

But, for example, I don't have incoming.telemetry.mozilla.org (or whatever it is) blocked because Firefox has a checkbox within the app to opt in.  And I personally do let them collect telemetry on my Firefox installs!  Because I can go to about:telemetry and https://telemetry.mozilla.org/ to see what it's all about.  It's just boring old diagnostics just like Bugfender might collect.  Still, they already give me a choice in the matter and show me what it is.  That's fine w/ me.

**Comment by spirillen** [comment]
With the risk of actually only wasting my time..

> Bugfender only helps them the data they need for debugging purposes

Such as GPS locations? altitudes (high above the waterline) Yeps, you live on 5 floor... bingo, where the local phone book to have my sales team calling you 24/7 about a hole bunch of useless junk... Oh you are living in a social building complex, Super :+1: you are very likely an easy offer for my sales team...  and so on and so on....

That's why we (blacklists maintainer) are blocking unmoral peoples like you, Yep, this isn't about whats legal or not, it actually about moral. 

And honestly, I have been scouting around for the Monty Python episode where John Cleese sticks to one of the other, writing everything down on his notebook and at the end of the sketch he sells the information to everyone. and This show may be about 20 years old by now....

**Comment by jgimenez** [comment]
The problem is Bugfender does not offer a UI, so we can not force developers to have a checkbox. However, please note we require our customers to get consent before fetching data. From our TOS (emphasis mine):

> Customer will assume full responsibility and take all necessary measures to ensure that
> [...]
> (g) otherwise **obtains and maintains any required consents from End Users to allow Beenario (including its service providers) to provide or have provided the Services**, including without limitation consent for Customer, Beenario and other entities to access, monitor, use and disclose End User data
