### ISSUE TITLE
fls-na.amazon.com

### ISSUE THREAD

**Issue by dnmTX** [AdAway/adaway.github.io#195]
@jawz101  having trouble scrolling trough pictures(selecting next one) in imdb.com.
Sample Link: https://www.imdb.com/title/tt3464896/mediaviewer/rm1746065665?context=default&ref_=tt_pv_md_2
It's frozen and there are bunch off errors showing up in Chrome Tools. All of them pointing out to `fls-na.amazon.com`
![Capture](https://user-images.githubusercontent.com/34774426/99227575-0b776200-27b1-11eb-8477-d5a5f951e0ea.PNG)

Looks like `fls-na.amazon.com` redirects to `https://images-na.ssl-images-amazon.com/images/I/31YXrY93hfL.js` 
Could you please evaluate. Thank you 👍

**Comment by jawz101** [comment]
I dont get any errors when I view that page & scroll thru the images.  How are you using this list?  Like pi-hole or another ad blocker?

**Comment by llacb47** [comment]
@dnmTX that domain is not causing your issue.

**Comment by dnmTX** [comment]
Indeed it wasn't the mentioned domain but my adblocker(AdGuard) unfortunately. I'll dig in to it.
Thanks for the assist @jawz101 and @llacb47  and apologies for the inconvenience 😉 👍 
Closing....

**Comment by jawz101** [comment]
It's no problem.  I've had goofy things happen with Amazon domains in the past.  Some of them would cause inconsistent breakage in the Amazon Android App if you blocked them, for example.  It's always good to see if those cause problems to anyone so I'm glad to look for those edge cases.  imdb piqued my interest because they are owned by Amazon so IMDB eventually sprinkled in a bunch of Amazon stuff on their site.
