### ISSUE TITLE
False positive: a.vnecdn.net

### ISSUE THREAD

**Issue by S-a-l-a-d** [AdAway/adaway.github.io#198]
This is used for hosting user profile pictures.

https://vnexpress.net/7-nhom-quyet-sach-vua-duoc-quoc-hoi-thong-qua-4193787.html

**Comment by jawz101** [comment]
Thanks.  Removed.  I had previously pulled in a Vietnamese list from someone called BigDargon a long time ago and I didn't know how much of it might not be great https://github.com/bigdargon/hostsVN

**Comment by S-a-l-a-d** [comment]
Oh I see. hostsVN is a good list and is updated regularly. It has been removed

So you also source from other lists. I thought the way to update a list (which is AdAway here) was like:

- Pull other lists every time so we have up-to-date entries
- Merge them together
- Include our own entries
- Remove duplicates
- Process our own whitelist

**Comment by jawz101** [comment]
This list used to be based on my personal list called MobileAdTrackers.  At that time ( 2 years ago or so) I had sourced a few lists but since then I've tried to remove unnecessary entries so that it is strictly targeted to mobile ad/tracking companies (that is, not webpage ads/trackers).

For the most part this list is meant to be original except for those older merges.
