### ISSUE TITLE
Blocklist

### ISSUE THREAD

**Issue by tillcash** [AdAway/adaway.github.io#213]
mobileads.indiatimes.com

**Comment by spirillen** [comment]
The domain exist, however I have not been able to locate the domain, from ordinary visit, and a direct visit is giving the expected `HTTP code: 404 not found` 

Is there by any change you can extract a log, showing the domain is being used??

**Comment by jawz101** [comment]
@sprillen

One site I use is VirusTotal and check the relations tab

https://www.virustotal.com/gui/domain/mobileads.indiatimes.com/relations


It shows files that have been scanned which refer to that domain- by extracting all of the files in an app.  I think they get the Communicating Files section by actually simulating running the app in a virtual environment.

**Comment by tillcash** [comment]
https://i.imgur.com/QHpE4W5.png

**Comment by spirillen** [comment]
> @sprillen
> 
> One site I use is VirusTotal and check the relations tab
> 
> https://www.virustotal.com/gui/domain/mobileads.indiatimes.com/relations
> 
> It shows files that have been scanned which refer to that domain- by extracting all of the files in an app. I think they get the Communicating Files section by actually simulating running the app in a virtual environment. This one doesn't have that section but it's still contained in android apk files

I know You are fan of VirusTotal :smiling_face_with_three_hearts: But there are more than this to my question :smirk: 

1. what is the relation (backlog)
2. What is called, by now I have found the notorious tracking `1x1.gif`

And since the game is open, why not get more info/knowledge ?

@tillcash thanks, but it only shows a DNS lookup, not what was transferred :unamused: 

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | 1x1.gif | << | mobileads.indiatimes.com | 1 | image | `http://mobileads.indiatimes.com/favicon.ico` |
| +2 | \|\|indiatimes.com^$image,redirect-rule=1x1.gif | -- | mobileads.indiatimes.com | 1 | image | `http://mobileads.indiatimes.com/favicon.ico` |
| +2 | /mobileads. | -- | mobileads.indiatimes.com | 1 | image | `http://mobileads.indiatimes.com/favicon.ico` |
| +0 |  |  | mobileads.indiatimes.com | 1 | doc | `http://mobileads.indiatimes.com/` |
</details>

**Comment by tillcash** [comment]
Sorry my knowledge is limited.

**Comment by spirillen** [comment]
> Sorry my knowledge is limited.

You should never be sorry for not knowing :) Just ask, the most of us are more than willing to teach, give fifes etc.

And know you are on the right path of learning :school:

**Comment by jawz101** [comment]
added
