### ISSUE TITLE
Slack channel

### ISSUE THREAD

**Issue by PerfectSlayer** [AdAway/adaway.github.io#22]
Hi all contributors,

I am opening a Slack channel to easily communicate about the next versions of AdAway project: the app, the hosts file, translations and the website.
I would like to invite the @AnXh3L0 @jawz101 and @smed79

Could you send me an email to `perfect slayer @ adaway . org` (without space) so I could invite you to the channel?

Regards

**Comment by jawz101** [comment]
hey.  Sorry I haven't responded.  I'm not much for signing up for a new chat service but if you want to use my list as is I'm all for it.  I continue to do little fixes every now and then.

Also, I just [compiled a list](https://github.com/jawz101/MobileAdTrackers/wiki/Other-lists-that-use-this-list) of other lists that source the MATS list.  I just found out NextDNS uses it too which is kinda cool.  Since Mozilla is now including them as a choice in [Firefox for DoH servers](https://blog.mozilla.org/blog/2019/12/17/firefox-announces-new-partner-in-delivering-private-and-secure-dns-services-to-users/) I thought that was interesting.  And LEDE/OpenWRT simple adblock addon includes it as a default list as well as Blokada.  So it makes me feel comfortable that it would be safe for Adaway

**Comment by PerfectSlayer** [comment]
No problem. Feel free to reach me if you change your mind.

About your list, do you think you could push an update here from times to times when you think it is fine for AdAway? Or would you rather we fetch it from your repository instead?

**Comment by jawz101** [comment]
Since the Adaway list is what everyone recognizes, it makes more sense to just pull my list once and I let my original copy fizzle out.  I'll fork it and submit pull requests back upstream to Adaway.

Seeing how the StevenBlack hosts file issue tracker plays out, it's a lot of him saying "report it to the original source."  That sounds like a constant game of phone tag.

I rarely get issues reported to me and have to go seek them out.  Recently, I reached out to another list maintainer who had [a bunch of feedback](https://www.reddit.com/r/oisd_blocklist/comments/dwxgld/dbloisdnl_internets_1_domain_blocklist/fbdxq51/) which was a first and in the past few days I cleaned up some quirks.  I disagree w/ about 1/2 of the ones reported but the other half I got rid of after researching the companies to see if it was truly mobile ad/tracking and sometimes testing the breakage myself.  But having the Adaway list be its own source would make it easier for the community to weigh in.

@AnXh3L0 @smed79

**Comment by PerfectSlayer** [comment]
I am glad you choose AdAway to move your list to.

As for @AnXh3L0 I grant you the rights on the repository in order to manage the list by yourself (you won't have to make PR but you still can if you want advices from the others 😉 ) and handle its issues (you will need it to close issues that you didn't create).

I can also pin an issue in https://github.com/AdAway/AdAway/issues to ask user to post hosts issues in this repository.

If everything is fine to you, just update #13 and let me know so I can set your rights 🤝

**Comment by jawz101** [comment]
@PerfectSlayer do you want to start the slack channel idea up again?  or Telegram or riot.im?  I have accounts on the latter 2 already.  I just want to make sure you have a way to get to me quicker if you have any questions/concerns

**Comment by PerfectSlayer** [comment]
@jawz101 I already opened the slack channel. Vankog (translation) and @AnXh3L0 (website) joined it.

Send me an email (see first post) to I could send you an invite back :wink:
