### ISSUE TITLE
Block Pre rolled Video Ads and Banner Ads on https://xhamster.com/

### ISSUE THREAD

**Issue by Jpersh27** [AdAway/adaway.github.io#241]
Hello @jawz101

Disclaimer: The website contains NSFW content. 

• I am currently using the Default Host File list for AdAway at this default URL- https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt

• I am currently using this Host File list inside the IDM+ browser application on my Android 10 device and I'm having issue with Ads on the mobile version of the website xhamster.com in specific. 

• The first Ad in question are pre rolled video ads that are 20 seconds in length and make you wait 10 seconds before you skip them and access the videos.

• The second Ad in question is a banner Ad that says “Chat with xhamster live girls now" below the xhamster video player.

• I have attached two screenshots below and blurred the NSFW contents of the Ads in question. 

![IMG_20210420_022746.jpg](https://user-images.githubusercontent.com/77606699/115347947-0a8f9580-a180-11eb-9a5e-180de16815dc.jpg)

![IMG_20210420_022619.jpg](https://user-images.githubusercontent.com/77606699/115347960-0cf1ef80-a180-11eb-858b-1a88f690c4ea.jpg)

**Comment by jawz101** [comment]
AdAway is intended primarily for mobile application ads and analytic companies.  Webpage ads are not in scope for this blacklist.

Also, if they're ads playing during a video stream, they're either embedded or using some mechanism in the video player to inject the ads.  I would be more inclined to recommend a different ad blocker mechanism altogether because a host file block list may not be sophisticated enough.  It could end up just blocking a video from playing instead of cutting out a piece of code triggering the ads.

I'd suggest either trying AdGuard for Android or Firefox for Android with the uBlock Origin extension as both of these support adblock plus syntax rules which can pull apart a webpage to block a particular thing.


https://adguard.com/en/welcome.html


But before that you may want to try AdGuard's DNS or NextDNS on your device in the Android Private DNS settings.

I'm just throwing some ideas out there but AdAway blocklist won't and likely can't catch in-video ads like that.
