### ISSUE TITLE
Blocking smassets.net breaks surveymonkey.com

### ISSUE THREAD

**Issue by grantemsley** [AdAway/adaway.github.io#245]
prod.smassets.net and cdn.smassets.net were both recently added.

Appears to be a CDN, and blocking them breaks sites like surveymonkey which load all their CSS/JS from those domains.

**Comment by jawz101** [comment]
removed.  thanks.

**Comment by spirillen** [comment]
Let me put a note for this decision.

Surveymonkey is TrackWare.... They are used to collect personal identifiable data about you, That's the short version, this said, removing `*.smassets.net` for accessing a tracking site/"service" is not among what I would have done.

My suggested solution would be to add a note in the wiki about this, leaving the real choice to the end user, rather than exposing them without any warning/information about what is about to happen.

Just my 2 (€) cents

-------

Did make a note(writing) about Surveymonkey and alike's in the past someway about how they are collecting the data about the sheep's, but it might have been in my older [Trac](https://trac.edgewall.org/) setup :shrug:
