### ISSUE TITLE
Remove schneidercorp.com

### ISSUE THREAD

**Issue by llacb47** [AdAway/adaway.github.io#27]
Please remove this entire section from the hosts file:

```
# [schneidercorp.com]
0.0.0.0 beacon.schneidercorp.com
0.0.0.0 beaconbeta.schneidercorp.com
```

These websites are not ads or tracking, they are "interactive public access portals" that allow access to local government property information and maps.

**Comment by jawz101** [comment]
Thanks.  removed

**Comment by spirillen** [comment]
This domain is listed at hphosts

hphosts_ad_servers/domain.list:beacon.schneidercorp.com

https://hosts-file.net/default.asp?s=beacon.schneidercorp.com

So I would leave that one, until more whitelisting documentation is applied

**Comment by jawz101** [comment]
hphosts is pretty liberal with their blocking.  I visited the company's website and they looked like almost a land surveying company http://schneidercorp.com

and the subdomain hasn't been seen in any Android apps on VirusTotal

https://www.virustotal.com/gui/domain/beacon.schneidercorp.com/relations

If I saw some activity on VirusTotal > relations tab that said it has been seen in some random Android apk that might clue me in on whether it might come from a mobile app.  Otherwise, I tend to definitely go ahead and remove them at that point.

I've reached out to VirusTotal before to see if I could batch scan a bunch of domains to see if they had any relations to Android apks (seen in their file data or network activity seen in a simulated/emulator environment) but they don't have that capability.

**Comment by spirillen** [comment]
:smile: 
Now you are saying VirusTotal 
- https://www.virustotal.com/gui/domain/beacon.schneidercorp.com/relations
- https://www.virustotal.com/gui/file/8a62e06a6d6dd1f91bddc89b6616b11dcab9059d5b95cdaf3a31a1cdd63e1411/detection
- https://www.virustotal.com/gui/file/e04849086d61a8aee6952eb00cb4f75a5bd6451e22d3560138615924a7592fdd/detection
 :smiley: 

Admitted haven spend much time on this, but all those red markers will make me take a deeper look on this.

**Comment by llacb47** [comment]
There are no red markers... please be reasonable

**Comment by jawz101** [comment]
Regardless, you're looking at a scan of Windows executables in those links.  If this is an Android mobile adware list, why would it be necessary to include domains related to Windows programs?

My reasoning is to keep this to just the subset of domains related to mobile adware/tracking- i.e not Windows malware, web-page ads, etc.

Adaway has always been specifically mobile adware domains- I just wanted to update it because it hadn't been touched since 2016.  It could use more removals than additions at this point.

**Comment by spirillen** [comment]
@llacb47 

![image](https://user-images.githubusercontent.com/44526987/72938995-4d3fa380-3d6c-11ea-9f40-3a8d476cc6c1.png)

![image](https://user-images.githubusercontent.com/44526987/72938578-81ff2b00-3d6b-11ea-9f9a-aa10c3543a32.png)

@jawz101 as said, haven't spent much time on it when i wrote the feedback. It was a note to me and other that there might be good reasoning in blocking the given domain, do to the detections and for help keeping network safe, this could be a argument to also keep it in your list. 

For my point of view I have decided to keep this domain blocked for the number of viruses hosted by this domain and it's history for doing so.

What you choose it entirely up to you. :smiley:
