### ISSUE TITLE
Remove bugsnag

### ISSUE THREAD

**Issue by swrobel** [AdAway/adaway.github.io#29]
[Bugsnag](https://www.bugsnag.com/) is a useful exception monitoring tool for developers and has nothing to do with ads, so I don't see what it's on this list. I'm not related to the company in any way other than I use & love their product. If there's some ethical stance about what they're doing that I'm missing, then I'd suggest removing `app.bugsnag.com` at a minimum, which is just the url of their web app that I log into to see tracked exceptions. However, I think all of their domains should be removed from the list.

**Comment by jawz101** [comment]
removed.  Thank you

**Comment by spirillen** [comment]
For cross references:

This domain is listed on @quidsup https://gitlab.com/quidsup/notrack-blocklists/blob/master/notrack-blocklist.txt#L840 

So why have he chosen to block this domain at second level? Let's await his answer as I have found two third level records from an initial load in rpz.mypdns.cloud

**Comment by jawz101** [comment]
host files don't support regex/wildcard entries.  If you want to block bugsnag subdomains you have to specify each one or use some solution that supports wildcards.

**Comment by spirillen** [comment]
I'm not doing hosts files.... I'm working with [RPZ](https://www.mypdns.org/wiki/Rpz) (Response Policy Zones) which do support wildcard.

But as it could have interest for both of us, I left the cross reference here :wave:

**Comment by quidsup** [comment]
I can't remember the reasons, but I'm not impressed having looked through their privacy policy. https://docs.bugsnag.com/legal/privacy-policy/

They contradict themselves saying they collect and don't collect personal information from users and guests over different sections.
Section 3.4 shows they're carrying out analytics with Cookies and Pixel tags. 

That kind of activity is exactly what the NoTrack blocklist is trying to prevent.

**Comment by jawz101** [comment]
cookies and pixel tags are web technologies.  For the Adaway list, it really should be entries that involve mobile apps and since the mobile sdk's are for actual debugging I'm not going to keep them.

For example: you visit https://www.bugsnag.com/ (the website) and they have segment.com, licdn.net (Linkedin), cookiehub.net, and Google Fonts & ajax apis.  If they do some sort of analytics when visiting their website, they probably have a policy applicable to their website.  The actual mobile SDK people use for debugging their apps would have to allude to anything other than debugging a developer's apps.  From what I saw, it doesn't, so I don't consider its product offering as ads or tracking.
