### ISSUE TITLE
Breaks Amazon app on Android

### ISSUE THREAD

**Issue by nkbyrne** [AdAway/adaway.github.io#291]
Current version causes Amazon app to report an "oh no" issue.

**Comment by jawz101** [comment]
Only when you click sponsored search results

**Comment by nkbyrne** [comment]
Mine was doing it as soon as I tried to search.

**Comment by nkbyrne** [comment]
Mine was doing it as soon as I tried to search.

**Comment by Eiz7Roch** [comment]
whitelisting 
fls-eu.amazon.co.uk
aan.amazon.co.uk

Stops the "oh no" 's

**Comment by nkbyrne** [comment]
Whitelisting 
fls-eu.amazon.co.uk
aan.amazon.co.uk

stops the errors

**Comment by jawz101** [comment]
fls-*.amazon.* DNS entries are associated with the Forrester Log Service .  page 23 or 31 in this document

https://docs.aws.amazon.com/workspaces/latest/adminguide/workspaces-ag.pdf

And from the Forrester site there is a blog post
[Amazon Leverages New Practices For Innovation And Growth Based On Customer Obsession](
https://www.forrester.com/report/learn-from-amazons-approach-to-innovation-and-experimentation/RES176284)

**Comment by jawz101** [comment]
I went ahead and removed all *.amazon.com and *.amazon.co domain entries.

https://github.com/AdAway/adaway.github.io/commit/4d68e148b6261636317f6e5f8c0aaa0f4b8168f7

Thank you for the feedback.  Sometimes I sit on some choices for a while with some entries that break a thing but you wish they didn't do.

**Comment by nkbyrne** [comment]
Great, been using the list on pfsense for a while with no issues. Guess Amazon changed something.

**Comment by jawz101** [comment]
I've used it on pfBlocker as well.  And a pi-hole.. and NextDNS... and NetGuard or AdGuard on my phone :/

I've seen the doggies before but it happens for if I click on something that turned out to be a sponsored product or if a banner advertises a special.  I also hit the north america fls-na one since I'm here and I had a bunch of different country-specific ones.

Aside from ads & trackers, I try to catch things were a company is trying to steer your purchase decisions.  Like I started buying cheap bluetooth earbuds for a while and I had to stop.  I think I have 10 pairs or so.
