### ISSUE TITLE
RevenueCat Purchases get blocked

### ISSUE THREAD

**Issue by rpolenthon** [AdAway/adaway.github.io#299]
Hey,
please consider removing api.revenuecat.com from the list. This API is no adware, it is a payment API for many apps out there that use it for making multi platform in app purchases and offers easier.

Feel free to ask any further questions.

Cheers,
Ron

**Comment by jawz101** [comment]
https://github.com/StevenBlack/hosts/pull/1837

**Comment by dnmTX** [comment]
Wow...they're like roches man. Hey Ronnie @rpolenthon what happened bruh? Wallets got thinner?
Shame though,just in time for Christmas 😄

**Comment by Cyral** [comment]
> Wow...they're like roaches man. Hey Ronnie @rpolenthon what happened bruh? Wallets got thinner? Shame though,just in time for Christmas 😄

Yes, wallets thinner because AdWay users cannot upgrade or access their paid content within my app. Please have a closer look at what the service actually is, it is a wrapper around the iOS/Android subscription APIs, not related to ads or user tracking.

**Comment by spirillen** [comment]
This is SPAM!! Sorry @jawz101 but this issue is to my opinion getting out if hand.

Group inviting ping to previously involved people:
@rpolenthon
@jawz101 
@Cyral 
@francocorreasosa
@jeiting
@rkotzy

I have setup a issue here: https://mypdns.org/my-privacy-dns/matrix/-/issues/4142 to try to determine what actually is going on in this case,  The reason is this issue + the one at sb/h have going haywire and one group have put them self to the left site and the other group is on the right side. Let's use facts to make our decisions. Please do that in preciously mentioned issue. 1 rule is "Stick to the issue or get banned"
