### ISSUE TITLE
Suggested ad domain additions

### ISSUE THREAD

**Issue by kthchew** [AdAway/adaway.github.io#322]
I found a few advertising domains contacted by the Musi app on iOS. These parent domains all seem to already be in your hosts file other than `inhousedsp.com`:

```
vg-new-hb.rayjump.com
vg-aws-us-east-1a-hb.rayjump.com
vg-aws-us-east-1b-hb.rayjump.com

ic.de.inmobi.com
dspbeacons.error.ihasdsp.inmobi.com
s.iff.inmobi.com

supply.inmobicdn.net
i.l-dsp.inmobicdn.net

imp-lb-us2.jampp.com
static.jampp.com

v-ak.chartboost.com

inhousedsp.com
content.inhousedsp.com
```

From the (pretty plain) content of `http://inhousedsp.com/`, it seems like this domain is owned by Dataseat Ltd (`https://www.dataseat.com/`), an ad-tech company. I've seen `rtb-lb-us-east.dataseat.com` in my Pi-hole logs, although not from Musi (I'm not sure exactly where it came from).

**Comment by jawz101** [comment]
good stuff!  thanks!

**Comment by jawz101** [comment]
I appreciate that you picked these sorts of domains for this particular blockist.  That is, mobile analytics and ads.

If you would ever consider the opportunity to take the reigns of the list... I just want to throw out the offer.

Maybe 4 years ago I was maintaining a mobile ads list that had some popularity and asked if I could take over the AdAway list because it didn't really do anything at the time.  It represented maybe a few dozen mobile tracking companies our phones were talking to tons more as new tracking companies opened up.

I've been only Android and these companies have the same analytic products for iOS as well and may have some server endpoints for talking to one or the other so I miss out on seeing the iPhone ones.

**Comment by kthchew** [comment]
Unfortunately, I think I'll have to reject that offer. I likely won't have the time/resources to maintain the list in the long-term, I'm sorry. I also have a bit of the opposite problem you have; I only use iOS and don't use Android, so I'd also miss those Android-specific domains. If I find any more of these domains, I'll still report back though!

Thank you for your work on maintaining this list, it's really appreciated.
