### ISSUE TITLE
Please whitelist: edge1.certona.net

### ISSUE THREAD

**Issue by durablenapkin** [AdAway/adaway.github.io#43]
`edge1.certona.net` is needed in order to load search results on Canadian Tire. I tested several times locally and narrowed it down to this entry.

Example: https://www.canadiantire.ca/en/search-results.html?q=cat%20scratch

Thanks! (cc'ing @StevenBlack)

```
/home/data# grep -r "certona" ./
./adaway.org/hosts:# [certona.net]
./adaway.org/hosts:127.0.0.1 edge1.certona.net
```

**Comment by jawz101** [comment]
done

**Comment by StevenBlack** [comment]
@jawz101 and @durablenapkin here's my take.

It's not sufficient that a domain is critical to some facet of operation of a commercial site.

If a domain is used for tracking, adware, or malware, then it should remain blocked; sites that depend on sketchy services should not be given a free pass.

If however the domain is listed, and we're unsure why, then remove it.

**Comment by spirillen** [comment]
Sounds pretty contra-addictive to https://github.com/StevenBlack/hosts/blob/c53b8177748342aa6b681dccbc59ec3b648fc39b/hosts

**Comment by jawz101** [comment]
The adaway list had been dead since 2016 and half of the entries pointed to dead domains.  A month ago I took over and based it on a list I had been maintaining at https://github.com/jawz101/MobileAdTrackers

Once it was in a list with more exposure, some of it's false positives have crept up.  I'm trying to fix these breakages as reported and find a way to scrub these without reducing some of the benefits of catching some of the mobile adware domains the list introduces that have been observed since 4 years ago.

**Comment by durablenapkin** [comment]
Much appreciated @jawz101!
