### ISSUE TITLE
What lists are being used

### ISSUE THREAD

**Issue by peace2000** [AdAway/adaway.github.io#45]
Hi! What lists you use to block ads?

**Comment by jawz101** [comment]
none.  It's me running apps and seeing what they do.  A couple of years ago I did some experimentation with importing a few other lists but I'm trying to keep trimming that effort back down.  This is just me and others who observe mobile ad and analytic traffic.

**Comment by peace2000** [comment]
All right nevermind then. :)

**Comment by jawz101** [comment]
sometimes I like those lists but I hate how many of them there are

**Comment by peace2000** [comment]
I understand that. I was wondering that if Easylist and it's language based variants would be ok?

**Comment by jawz101** [comment]
how do you mean?

**Comment by peace2000** [comment]
The reason I opened this issue was to ask if you would be willing to add The Finnish Easylist as part of Adaway's filter lists as I presumed that you are using the main (English) Easylist which is quite popular.

**Comment by jawz101** [comment]
Even if I did, I could only use a subset of the items because Adblock+ syntax is meant to have the ability to carve out elements of a web page and are more appropriate for browser-based ad blockers.  Adaway is a hosts file format list which means it just block whole domains if that domain is even requested.

Looking at [that list](https://raw.githubusercontent.com/finnish-easylist-addition/finnish-easylist-addition/master/Finland_adb.txt) `ticketmaster.fi##div[id^="ad-slot-"]` means block a bit of the ticketmaster.fi web page with a div tag starting with the string 'ad-slot-'.  I couldn't just block all of ticketmaster.fi because you'd be unable to buy your concert tickets.

On the other hand, the section on the list labeled NETWORK FILTERS behave much like a host file because it's a pretty basic rule to block a domain if it is 3rd party.

`||ad.citycdn.fi^$third-party` just means block that ad.citycdn.fi if it appears third party on a webpage.  I could strip out the `||` and `^$third-party`` and just make it a host file rule because you probably never browse to that domain directly, but it's just as well to use AB+ (Easylist) rules in a web-based ad blocker such as Adblock+ or uBlock Origin and use a dns-based/host file list in a computer's hosts file, a mobile adblocker such as Adaway/NetGuard/Blokada, or on a pi-hole or other DNS resolver.

**Comment by peace2000** [comment]
All right, I didn't realize at first that Adaway's idea is to work as a hosts list. But ok, thank you for your explanation. :)

**Comment by spirillen** [comment]
Now you are mentioning TV's :tv: I've got some records for Samsung owners [here](https://www.mypdns.org/ticket/65)

PS: if anybody knows about any shady domains used by others like LG or Sony, please do share it with the rest of us.

PPS: If you can speak Italian or even know a lot more about [mediaset.it](https://www.mypdns.org/ticket/190) I would appreciate any sharing of knowledge for how much it would be possible to block to enhance your privacy
