### ISSUE TITLE
use-application-dns.net should not be sinkholed

### ISSUE THREAD

**Issue by WaLLy3K** [AdAway/adaway.github.io#56]
https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet

> Firefox will attempt to resolve this domain using the DNS server(s) configured in the operating system of the device, and examine the result. The result will be considered negative if:
> * A response code other than NOERROR is returned, such as NXDOMAIN (non-existent domain) or SERVFAIL
> * A NOERROR response code is returned, but contains neither A nor AAAA records

> The result will be considered positive if:
> * The query completes with NOERROR and contains A or AAAA records (or both)

> A negative result will be a signal to disable application DNS, i.e. DoH.

By adding `use-application-dns.net` as an A record, this blocklist ([as well as others](https://github.com/StevenBlack/hosts/issues/1172)) is signalling that DoH should be enabled which is an issue for DNS based adblockers that often use this list such as [Pi-hole](https://github.com/pi-hole/pi-hole/issues/3167).

Thanks :)

**Comment by jawz101** [comment]
I thought this would force DoH off but instead it sounds like it just switches the resolution from actually resolving to Mozilla's server to simply resolving successfully to a 0.0.0.0 IP for pi-hole.

For the Android app [NetGuard it returns a DNS response of 3](https://github.com/M66B/NetGuard/commit/5e09b785939e0c1ab81d51f3c7924cb637956063) (or NXDOMAIN) when a hostfile includes a domain.

I have a pi-hole at home as well so my question is this: how would have that domain return NOERROR (NXDOMAIN/SERVFAIL) response if you cannot include it a block for it?  It sounds like to get it to work, you would have to have it on a list but then configure your blocker to respond to blocks w/ an NXDOMAIN or SERVFAIL response rather than resolving to a 0.0.0.0 address, correct?

Scenario 1: have it on a blocklist.  It resolves to 0.0.0.0 and Firefox enables DoH

Scenario 2: it isn't on a blocklist.  It resolves to 63.245.208.212 and Firefox enables DoH

Scenario 3: have it on the blocklist and change pi-hole config to respond with [NXDOMAIN response instead of a 0.0.0.0 address](https://docs.pi-hole.net/ftldns/blockingmode/)

I would think you would have to change pi-hole's configurations AND have it on a blocklist to get pi-hole to affect Firefox, right?

**Comment by WaLLy3K** [comment]
If you do a lookup of `use-application-dns.net` to a standard upstream resolver such as Cloudflare, it will return the IP of `63.245.208.212`. With the [latest version of Pi-hole](https://github.com/pi-hole/pi-hole/commit/1c74b41869887afb87cc818e1be54d5a108db866), FTL will return `NXDOMAIN` for that query.

**Comment by jawz101** [comment]
but then for NetGuard on Android users it will pass through since it doesn't have such a hardcoded rule.

**Comment by WaLLy3K** [comment]
I'm not too sure how the Android side of things would work - would there not be a system-wide (or Firefox application-wide) setting to toggle this functionality somewhere?

**Comment by jawz101** [comment]
I don't know.  I'm thinking about it.  I guess I will remove it.  Currently in the Firefox for Android app you can manually disable DoH.  I don't know if they take that ability away in the new Firefox Preview version, though.

**Comment by dschaper** [comment]
Following up:

1. **Pi-hole v4.4 default - canary domain on blocklist**
A/AAAA returns `0.0.0.0` / `::` and DoH is enabled.
2. **Pi-hole v4.4 default - canary not on blocklist**
A/AAAA returns `NXDOMAIN` from the added `server=/use-application-dns.net` entry added in this version and DoH disabled.
3. **Pi-hole less than v.4.4 - canary not on blocklist**
DoH enabled. 
4. **Pi-hole (any version) in NXDOMAIN blocking mode - canary domain on blocklist**
A/AAAA returns `NXDOMAIN` from canary on blocklist and DoH disabled.

**Comment by spirillen** [comment]
Just to follow up on this, as there unfortunately have been made changes to this...

![image](https://user-images.githubusercontent.com/44526987/79702223-9340d080-82a3-11ea-9044-58573dab5ef5.png)

I can unfortunately confirm this misbehavior from FF

![image](https://user-images.githubusercontent.com/44526987/79702251-bec3bb00-82a3-11ea-865c-b919fc40b0ee.png)

```
dig use-application-dns.net 

; <<>> DiG 9.11.5-P4-5.1ubuntu2.1-Ubuntu <<>> use-application-dns.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 43650
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;use-application-dns.net.       IN      A
```
