### ISSUE TITLE
Unblock api.ipify.org

### ISSUE THREAD

**Issue by atestig** [AdAway/adaway.github.io#57]
Hi

Was it really necessary to add this:

127.0.0.1 api.ipify.org

to the list?

This broke, among other things, an internal monitoring tool and a dynamic DNS updater.
(also the block is even incomplete since you guys missed api6.ipify.org)

All they do is provide your public IP address back to you via a free API that anyone can use without signing up or any other restrictions. Nothing is logged either. :/

**Comment by jawz101** [comment]
fixed

**Comment by spirillen** [comment]
A little comment, first of i believe it's wrong to unblock this domain, but secondly, since it have been decided, I would suggest to add `geo.ipify.org` if it's not already there. 

This would at least give a little privacy, as the IP already is available in the log anyway, they would have to do a either manual lookup, or a resource costly bridging between `api.` and `geo.` which anyway is easily setup for both domain as a proxy forwarder.

But it would cost them on the profit of others....

There is also these comment by 
- https://github.com/easylist/easylist/issues/2810#issuecomment-491592633 @ryanbr 
- szepeviktor @szepeviktor

I would therefor urge you to a reconsideration of this choice.

Own note: ref: https://www.mypdns.org/T605
